spring.application.name=Marketplace-API
spring.datasource.url=jdbc:postgresql://cb681qjlulc2v0.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/$dd126nphs5n30
spring.datasource.username=udjqbjl40vg947
spring.datasource.password=p112a40e4b6342dfd58b4c53315ebe6fd4bcd446501091f4a27ac4123c3251f18




spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
